name: build
on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Get repo name
        id: get_repo
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY#*/}

      - name: Setup java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'

      - name: Build artefacts
        run: |
          gradle build --no-daemon
          mkdir data
          cp ./build/libs/${GITHUB_REPOSITORY#*/}*.jar ./data/app.jar
          echo "Branch: ${{ github.ref}}"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{steps.get_repo.outputs.REPO}}
          path: ./data/app.jar
